### ISSUE TITLE
Can't start WebInterface

### ISSUE THREAD

**Issue by 1kane** [sdenton4/pipic#17]
when i try to start the server with 
 `/home/pi/pipic/djpilapse/manage.py runserver 192.168.0.5:8000`                                                                              

`Traceback (most recent call last):
  File "/home/pi/pipic/djpilapse/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 306, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 229, in close_all
    for alias in self:
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 223, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 156, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 111, in __init__
    raise ImproperlyConfigured("The %s setting must be a list or a tuple. " % setting)
django.core.exceptions.ImproperlyConfigured: The TEMPLATE_DIRS setting must be a list or a tuple.
`

**Comment by Nivin37** [comment]
I have the same issue as well. 
Can I expect help?

**Comment by sdenton4** [comment]
Hey, just made the TEMPLATE_DIRS a tuple, but haven't tested the interface.  So not sure if you'll just hit another error.  I don't have a bunch of time for this one at the moment, but I'm happy to review pull requests.

The non-web script (timelapse.py) just got a bunch of updates in December, and may be a bit less problematic.

**Comment by labrax** [comment]
I get a similar issue, I expect it is due to another version of django. Could you please provide the version that it worked?

My error is: ImportError: cannot import name patterns

**Comment by ccdanieldb** [comment]
Hello, having the same problem with the web server.  But I do not mind doing everything from the command line.  Would it be possible for you to add a few notes here or on the code page for this project on how to get the time lapse started from an ssh command line, or desktop (via vnc or ms Remote Desktop).  I am trying to get this working on my Raspi with the new as a all sky camera.  

Just running the below did not work very well.

`pi@raspiHQcam2:~/pipic $ python timelapse.py`
`Traceback (most recent call last):`

`  File "timelapse.py", line 3, in <module>`

`    import Image`

`ImportError: No module named Image`

`pi@raspiHQcam2:~/pipic $ python3 timelapse.py`

`  File "timelapse.py", line 132`

`    print "Failed to disable LED: " + e`
                                  ^
`SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Failed to disable LED: " + e)?
`
pi@raspiHQcam2:~/pipic $

**Comment by sdenton4** [comment]
Hi, looks like you a) don't have the Image python package, and b) are using Python 3 (which requires parentheses for print statements). This project is no longer maintained; feel free to send a pull request, though, or fork and fix.

**Comment by ccdanieldb** [comment]
Do you have a link for the Image python package?  I had Pillow installed and was thinking that was what you were referring to or maybe PIL.  So I uninstalled Pillow, as it was already installed, then tried to install PIL.  That turned out to be almost impossible, at least for a guy like me of limited intellect. (it's way out of date anyway)  But I was able to finish off a 12 pack, well trying to do so.  In any case, it was about then as I was pondering the Norm theory on beer and brain cells that I took another look at your post and realized that I may have been moving in the wrong directing.
